# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-02-06 17:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField(null=True)),
                ('date', models.DateField(verbose_name='date')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='last modified')),
                ('registration_date', models.DateField(verbose_name='registration date')),
                ('description', models.TextField()),
                ('source', models.URLField()),
                ('deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('wounded', models.PositiveIntegerField(blank=True, null=True)),
                ('missing', models.PositiveIntegerField(blank=True, null=True)),
                ('arrested', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths_security_forces', models.PositiveIntegerField(blank=True, null=True)),
                ('wounded_security_forces', models.PositiveIntegerField(blank=True, null=True)),
                ('missing_security_forces', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths_perpetrator', models.PositiveIntegerField(blank=True, null=True)),
                ('wounded_perpetrator', models.PositiveIntegerField(blank=True, null=True)),
                ('missing_perpetrator', models.PositiveIntegerField(blank=True, null=True)),
                ('tag_ids', models.TextField(blank=True, default='')),
                ('location_inaccurate', models.NullBooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_key', models.IntegerField(help_text='For ordering Incident Types', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Incident Types',
                'ordering': ['-order_key'],
            },
        ),
        migrations.CreateModel(
            name='KeySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('name_fr', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'name_fr')]),
        ),
        migrations.AddField(
            model_name='incident',
            name='mention_list',
            field=models.ManyToManyField(blank=True, to='incident.KeySource'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='tags',
            field=models.ManyToManyField(blank=True, to='incident.Tag'),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident.IncidentType'),
        ),
    ]
