# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField()),
                ('source', models.URLField()),
                ('deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('wounded', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_key', models.IntegerField(help_text='For ordering Incident Types', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Incident Types',
                'ordering': ['-order_key'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident.IncidentType'),
        ),
    ]
