# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='registration_date',
            field=models.DateField(auto_now=True, verbose_name='registration date'),
        ),
    ]
